export { default as exitToAppImg } from './exit_to_app.png';
export { default as brasileirao_assai } from './brasileirao_assai.svg';
export { default as check } from './check.png';
export { default as editIcon } from './pencil.png';
export { default as positiveLogo } from './positive_logo.png';
export { default as americaMg } from './club_logos/america_mg.svg'
export { default as athleticoPr } from './club_logos/athletico_pr.svg'
export { default as atleticoMg } from './club_logos/atletico_mg.svg'
export { default as bahia } from './club_logos/bahia.svg'
export { default as botafogo } from './club_logos/botafogo.svg'
export { default as bragantino } from './club_logos/bragantino.svg'
export { default as corinthians } from './club_logos/corinthians.svg'
export { default as coritiba } from './club_logos/coritiba.svg'
export { default as cruzeiro } from './club_logos/cruzeiro.svg'
export { default as cuiaba } from './club_logos/cuiaba.svg'
export { default as flamengo } from './club_logos/flamengo.svg'
export { default as fluminense } from './club_logos/fluminense.svg'
export { default as fortaleza } from './club_logos/fortaleza.svg'
export { default as goias } from './club_logos/goias.svg'
export { default as gremio } from './club_logos/gremio.svg'
export { default as internacional } from './club_logos/internacional.svg'
export { default as palmeiras } from './club_logos/palmeiras.svg'
export { default as santos } from './club_logos/santos.svg'
export { default as saoPaulo } from './club_logos/sao_paulo.svg'
export { default as vasco } from './club_logos/vasco.svg'